### PR TITLE
Documentation update

### PR DESCRIPTION
**Pull request by kdheepak**
- [x] I have reviewed the [Contributing Guidelines](../CONTRIBUTING.md)
- [x] I agree to license my contributions under the same license as in this repository (BSD 3 clause)

### CODE REVIEW

**Comment by kdheepak** [comment]
This is ready to be merged into `master`.

**Comment by phlptp** [comment]
@kdheepak  go ahead and merge this, not sure if it should be before or after #613 probably a squash and merge.

**Comment by kdheepak** [comment]
I'll do a rebase and merge this after #613.

**Comment by phlptp** [comment]
#613 is merged @kdheepak  so you can update this and merge when ready.

**Comment by kdheepak** [comment]
I've rebased on top of latest master and forced push here.

**Comment by phlptp** [comment]
Assuming it passed travis,  I think you can go ahead and merge, then update the gh-pages branch with the latest documentation.  Then we can do a final look through of that.

**Comment by phlptp** [comment]
@kdheepak  go ahead and do a squash and merge

**Pull request merged**
