### PR TITLE
update the timeout used in zmq comms

### PR DESCRIPTION
**Pull request by phlptp**
- [x] I have reviewed the [Contributing Guidelines](../CONTRIBUTING.md)
- [x] I agree to license my contributions under the same license as in this repository
- [x] I have verified that the tests pass

### Description

This partially addresses Issue #578

### Proposed changes

- Have the timeout on the ZMQ comms use the connectionTimeout variable from CommInterface instead of hard coded value
- use 0 timeout for some zmqComms_ss since 10ms was not particularly useful.

### CODE REVIEW

**Comment by phlptp** [comment]
@Jacobhansens  I would like to get any retry code you had in as well

**Comment by Jacobhansens** [comment]
What I had was a very quick but not too good solution. I basically introduced the possibility of an infinite loop. I will get a better version together today and share that here for you to look at.

**Comment by Jacobhansens** [comment]
@phlptp, please take a look at the retry logic I added. I tested it on my end and it works for me but I would appreciate your review on this as well.

**Comment by Jacobhansens** [comment]
@Phil, if you want I can go ahead and approve this one, but wanted to check with you as you mentioned  this might go beyond the ZMQ core and I am not sure if you want that to be part of this PR.

**Comment by phlptp** [comment]
I think we should revisit this at a later time but I am comfortable merging it.  I think this is part of a bigger issue on network resilience that isn't going to be resolved in the next week.  And will probably evolve as well expand the usage and scale.

**Comment by phlptp** [comment]
@Jacobhansens  go ahead and approve unless you see something that should be fixed.

**Pull request merged**
