### PR TITLE
Fix long long warnings

### LINKED ISSUE #107: warning messages from python build
Is there anything we can do about these warnings?
```
In file included from /usr/include/python3.4m/Python.h:78:0,
                 from /home/travis/build/GMLC-TDC/HELICS-src/build/swig/python/helicsPYTHON_wrap.c:149:
/usr/include/python3.4m/longobject.h:88:37: warning: ISO C90 does not support ‘long long’ [-Wlong-long]
 PyAPI_FUNC(PyObject *) PyLong_FromLongLong(PY_LONG_LONG);
                                     ^
/usr/include/python3.4m/longobject.h:89:54: warning: ISO C90 does not support ‘long long’ [-Wlong-long]
 PyAPI_FUNC(PyObject *) PyLong_FromUnsignedLongLong(unsigned PY_LONG_LONG);
                                                      ^
/usr/include/python3.4m/longobject.h:90:6: warning: ISO C90 does not support ‘long long’ [-Wlong-long]
 PyAPI_FUNC(PY_LONG_LONG) PyLong_AsLongLong(PyObject *);
      ^
/usr/include/python3.4m/longobject.h:91:15: warning: ISO C90 does not support ‘long long’ [-Wlong-long]
 PyAPI_FUNC(unsigned PY_LONG_LONG) PyLong_AsUnsignedLongLong(PyObject *);
               ^
/usr/include/python3.4m/longobject.h:92:15: warning: ISO C90 does not support ‘long long’ [-Wlong-long]
 PyAPI_FUNC(unsigned PY_LONG_LONG) PyLong_AsUnsignedLongLongMask(PyObject *);
               ^
/usr/include/python3.4m/longobject.h:93:6: warning: ISO C90 does not support ‘long long’ [-Wlong-long]
 PyAPI_FUNC(PY_LONG_LONG) PyLong_AsLongLongAndOverflow(PyObject *, int *);
```

### PR DESCRIPTION
**Pull request by kdheepak**
Fixes #107

### CODE REVIEW

**Comment by kdheepak** [comment]
I made the changes.

**Comment by phlptp** [comment]
the targets that get generated seem to be custom targets.  are they built though cmake or some custom swig stuff

**Comment by kdheepak** [comment]
These are built using swig. It looks like the warning don't appear in [clang](https://travis-ci.org/GMLC-TDC/HELICS-src/jobs/335294532#L2222) or in [gcc-6](https://travis-ci.org/GMLC-TDC/HELICS-src/jobs/335294528#L2304) but do still appear in [gcc-4.9](https://travis-ci.org/GMLC-TDC/HELICS-src/jobs/335294531#L2341).

**Comment by kdheepak** [comment]
Well, this PR didn't change anything. I just checked the old log and that also had the warning only for gcc-4.9.

**Comment by phlptp** [comment]
I guess that is probably because _helics is probably a C project in which case it wouldn't use the CXX_flags  probably need to change it CMAKE_C_FLAGS

**Comment by phlptp** [comment]
I really need to figure out how to fix the filter_message error.  That one has been nearly impossible to debug since I can't replicate it on any of my systems and doesn't occur in debug mode.  

anyway this seems to fix the warnings

**Pull request merged**
