### PR TITLE
fix the operation of the uninterruptible flag and add test checking it.

### PR DESCRIPTION
**Pull request by phlptp**
- [x] I have reviewed the [Contributing Guidelines](../CONTRIBUTING.md)
- [x] I agree to license my contributions under the same license as in this repository
- [x] I have verified that the tests pass

### CODE REVIEW

**Comment by Jacobhansens** [comment]
I checked this pull request with my simple example and I am not able to get the desired outcome. The case I run is a simple two federate case where each federate publishes one topic and then subscribes to the topic from the other federate. 

Federate 1 JSON config:
```
{
  "name": "fed1",
  "log_level": 2,
  "observer": false,
  "rollback": false,
  "only_update_on_change": false,
  "only_transmit_on_change": false,
  "source_only": false,
  "uninterruptible": true,
  "coreType": "zmq",
  "coreName": "",
  "coreInit": "1",
  "maxIterations": 1,
  "period": 1.0,
  "offset": 0.0,
  "timeDelta": 1.0,
  "outputDelay": 0,
  "inputDelay": 0,
  "publications":[
  {
    "key":"pub", 
    "type":"double",
    "unit":"m",
    "global":false,
    "info":"This is a random string containing some info for fed1 publication"
  }],
  "subscriptions":[
  {
    "key":"fed2/pub", 
    "type":"double", 
    "unit":"m",
    "required":false,
    "info":"This is a random string containing some info for fed1 subscription"
  }]
}
```

Federate 2 JSON config:
```
{
  "name": "fed2",
  "log_level": 2,
  "observer": false,
  "rollback": false,
  "only_update_on_change": false,
  "only_transmit_on_change": false,
  "source_only": false,
  "uninterruptible": false,
  "coreType": "zmq",
  "coreName": "",
  "coreInit": "1",
  "maxIterations": 1,
  "period": 1.0,
  "offset": 0.0,
  "timeDelta": 1.0,
  "outputDelay": 0,
  "inputDelay": 0,
  "publications":[
  {
    "key":"pub", 
    "type":"double", 
    "unit":"m", 
    "global":false,
    "info":"{\"fake\": \"This is a random string containing some json for fed2 publication\"}"
  }],
  "subscriptions":[
  {
    "key":"fed1/pub", 
    "type":"double", 
    "unit":"m",
    "required":false,
    "info":"{\"fake\": \"This is a random string containing some json for fed2 subscription\"}"
  }]
}
```

Before testing with the uninterruptible flag set to true I tested my case with it set to false (just to make sure everything runs as expected). The outcome of this experiment seems good:

Federate 1:
```
helics@quantum:~/valueFederate$ ./valueFed valueFed1.json 5
fed name -> fed1
config name -> valueFed1.json
pubs -> [fed1/pub]
subs -> [fed2/pub]
publication keys:
	 fed1/pub
subscription keys:
	 fed2/pub
entering init mode
entered init State
entered exec mode
delta time -> 5 seconds
stop time -> 11 seconds
############## TIMING ##############
    processed time 0
    requested new time 5
    requestTime call returned 1
####################################
received updated value of 0 at 1 from fed2/pub
############## TIMING ##############
    processed time 1
    requested new time 6
    requestTime call returned 2
####################################
received updated value of 1 at 2 from fed2/pub
############## TIMING ##############
    processed time 2
    requested new time 7
    requestTime call returned 3
####################################
received updated value of 2 at 3 from fed2/pub
############## TIMING ##############
    processed time 3
    requested new time 8
    requestTime call returned 4
####################################
received updated value of 3 at 4 from fed2/pub
############## TIMING ##############
    processed time 4
    requested new time 9
    requestTime call returned 5
####################################
received updated value of 4 at 5 from fed2/pub
############## TIMING ##############
    processed time 5
    requested new time 10
    requestTime call returned 6
####################################
received updated value of 5 at 6 from fed2/pub
############## TIMING ##############
    processed time 6
    requested new time 11
    requestTime call returned 7
####################################
received updated value of 6 at 7 from fed2/pub
############## TIMING ##############
    processed time 7
    requested new time 12
    requestTime call returned 8
####################################
received updated value of 7 at 8 from fed2/pub
############## TIMING ##############
    processed time 8
    requested new time 13
    requestTime call returned 9
####################################
received updated value of 8 at 9 from fed2/pub
############## TIMING ##############
    processed time 9
    requested new time 14
    requestTime call returned 10
####################################
received updated value of 9 at 10 from fed2/pub
############## TIMING ##############
    processed time 10
    requested new time 15
    requestTime call returned 11
####################################
about to exit
```

Federate 2:
```
helics@quantum:~/valueFederate$ ./valueFed valueFed2.json 1
fed name -> fed2
config name -> valueFed2.json
pubs -> [fed2/pub]
subs -> [fed1/pub]
publication keys:
	 fed2/pub
subscription keys:
	 fed1/pub
entering init mode
entered init State
entered exec mode
delta time -> 1 seconds
stop time -> 11 seconds
############## TIMING ##############
    processed time 0
    requested new time 1
    requestTime call returned 1
####################################
received updated value of 0 at 1 from fed1/pub
############## TIMING ##############
    processed time 1
    requested new time 2
    requestTime call returned 2
####################################
received updated value of 1 at 2 from fed1/pub
############## TIMING ##############
    processed time 2
    requested new time 3
    requestTime call returned 3
####################################
received updated value of 2 at 3 from fed1/pub
############## TIMING ##############
    processed time 3
    requested new time 4
    requestTime call returned 4
####################################
received updated value of 3 at 4 from fed1/pub
############## TIMING ##############
    processed time 4
    requested new time 5
    requestTime call returned 5
####################################
received updated value of 4 at 5 from fed1/pub
############## TIMING ##############
    processed time 5
    requested new time 6
    requestTime call returned 6
####################################
received updated value of 5 at 6 from fed1/pub
############## TIMING ##############
    processed time 6
    requested new time 7
    requestTime call returned 7
####################################
received updated value of 6 at 7 from fed1/pub
############## TIMING ##############
    processed time 7
    requested new time 8
    requestTime call returned 8
####################################
received updated value of 7 at 8 from fed1/pub
############## TIMING ##############
    processed time 8
    requested new time 9
    requestTime call returned 9
####################################
received updated value of 8 at 9 from fed1/pub
############## TIMING ##############
    processed time 9
    requested new time 10
    requestTime call returned 10
####################################
received updated value of 9 at 10 from fed1/pub
############## TIMING ##############
    processed time 10
    requested new time 11
    requestTime call returned 11
####################################
about to exit
```

Then I tested with the uninterruptible flag to true in Federate 1 and the simulation hangs with the following output:

Federate 1:
```
helics@quantum:~/valueFederate$ ./valueFed valueFed1.json 5
fed name -> fed1
config name -> valueFed1.json
pubs -> [fed1/pub]
subs -> [fed2/pub]
publication keys:
	 fed1/pub
subscription keys:
	 fed2/pub
entering init mode
entered init State
entered exec mode
delta time -> 5 seconds
stop time -> 11 seconds
31152-CYSre-s0yyM-lV4gF-S3StJ (1879048192):: core tick
31152-CYSre-s0yyM-lV4gF-S3StJ (1879048192):: core tick
```

Federate 2:
```
helics@quantum:~/valueFederate$ ./valueFed valueFed2.json 1
fed name -> fed2
config name -> valueFed2.json
pubs -> [fed2/pub]
subs -> [fed1/pub]
publication keys:
	 fed2/pub
subscription keys:
	 fed1/pub
entering init mode
entered init State
entered exec mode
delta time -> 1 seconds
stop time -> 11 seconds
############## TIMING ##############
    processed time 0
    requested new time 1
    requestTime call returned 1
####################################
received updated value of 0 at 1 from fed1/pub
31160-JTT2k-D5tK8-oLHsA-nhyNO (1879048193):: core tick
31160-JTT2k-D5tK8-oLHsA-nhyNO (1879048193):: core tick
```

Let me know if you need more information to reproduce.

**Comment by Jacobhansens** [comment]
Adding valueFederate.cpp code here as well as that might give you some insight as well:
```
/*
Copyright © 2017-2018,
Battelle Memorial Institute; Lawrence Livermore National Security, LLC; Alliance for Sustainable Energy, LLC
All rights reserved. See LICENSE file and DISCLAIMER for more details.
*/
#include <helics/application_api/ValueFederate.hpp>
#include <helics/application_api/queryFunctions.hpp>
#include <helics/application_api/Inputs.hpp>
#include <helics/application_api/Publications.hpp>
#include <thread>
#include <iostream>

int main (int argc, const char * const *argv)
{
    if (argc != 3) {
         std::cerr << "Expecting two arguments. You have entered " << argc-1 << " arguments" << std::endl; 
         return 0;
    }

    // string for the name of the federate configuration file
    std::string configString = argv[1];

    // loads configuration, registers interfaces and starts the federate
    //auto vFed = new helics::ValueFederate ("temp_name", configString);
    auto vFed = new helics::ValueFederate (configString);

    // some user messages
    std::cout << "fed name -> " << vFed->getName() << std::endl;
    std::cout << "config name -> " << configString << std::endl;
    
    //std::cout << "publication count -> " << vFed->getPublicationCount() << std::endl; 
    //std::cout << "subscription count -> " << vFed->getSubscriptionCount() << std::endl; 
  
    std::cout << "pubs -> " << vFed->query(vFed->getName(), "publications") << std::endl;  
    std::cout << "subs -> " << vFed->query(vFed->getName(), "subscriptions") << std::endl;  

    // returns a list of publication keys in the configuration file
    auto pubKeys = vectorizeAndSortQueryResult(vFed->query(vFed->getName(), "publications"));

    // returns a list of subscription keys in the configuration file
    auto subKeys = vectorizeAndSortQueryResult(vFed->query(vFed->getName(), "subscriptions"));

    // print out the publications for the user
    std::cout << "publication keys:" << std::endl;
    for(auto it = pubKeys.begin(); it != pubKeys.end(); ++it) {
        std::cout << "\t " << *it << std::endl;
    }

    // print out the subscriptions for the user
    std::cout << "subscription keys:" << std::endl;
    for(auto it = subKeys.begin(); it != subKeys.end(); ++it) {
        std::cout << "\t " <<  *it << std::endl;
    }

    // this federate is only built to handle one publication and one subscription. Will exit if that is not the case!!
    //if (vFed->getPublicationCount() > 1 || vFed->getSubscriptionCount() > 1) {
    if (pubKeys.size() > 1 || subKeys.size() > 1) {
        std::cerr << "This federate only supports one subscription and publication. You specified more and only the first one will be used!!" << std::endl; 
    }

    // get the id of the publication. In the future this could support more than one!
//    auto id = vFed->getPublicationId(pubKeys[0]);
    auto id = vFed->getPublication(pubKeys[0]);
    // get the id of the subscription. In the future this could support more than one!
//    auto subid = vFed->getSubscriptionId(subKeys[0]);
    auto subid = vFed->getSubscription(subKeys[0]);

    // we are done with the setup, start the initialization
    std::cout << "entering init mode" << std::endl;
    vFed->enterInitializingMode ();
    std::cout << "entered init State" << std::endl;

    // now enter execution state
    vFed->enterExecutingMode ();
    std::cout << "entered exec mode" << std::endl;

    double currentTime = 0;
    double currentTimeTemp = 0;
    double nextTime = 0;
    double stopTime = 11;
    double timeDelta = atof(argv[2]);;
    std::cout << "delta time -> " << timeDelta << " seconds" << std::endl;
    std::cout << "stop time -> " << stopTime << " seconds" << std::endl;
    // simple loop that count from 0 through 9 to test pub/sub
    do {
        currentTimeTemp = currentTime;
        // publish our variable
        //id.publish("sent at " + std::to_string(currentTime));
        id.publish(currentTime);

          // if our subscription is updated lets get the value
        if (vFed->isUpdated(subid))
        {
            // get the latest value for the subscription
            auto val = vFed->getDouble(subid);
            std::cout << "received updated value of " << val << " at "<< currentTime << " from " << vFed->getTarget(subid) << std::endl;
        }
         
        nextTime = currentTime+timeDelta;
        currentTime = vFed->requestTime ((helics::Time) nextTime);

        std::cout << "############## TIMING ##############" << std::endl;
        std::cout << "    processed time " << currentTimeTemp << std::endl;
        std::cout << "    requested new time " << nextTime << std::endl;
        std::cout << "    requestTime call returned " << currentTime << std::endl;
        std::cout << "####################################" << std::endl;
        
    } while (currentTime < stopTime);
            
    std::cout << "about to exit" << std::endl;
    // end the federate
    vFed->finalize ();
    return 0;
}
```

**Comment by phlptp** [comment]
any chance you can add a test case like I added but better matching your case.  there must be something with the two way transfer that is not being updated

**Comment by Jacobhansens** [comment]
Just added a test case to this branch that shows the hang I am getting. It does seem to be something with the two way transfer that locks the simulation.

**Comment by phlptp** [comment]
my guess is that the time_next is not being updated properly.  so it is sending the wrong times to the other federate,. so it can't advance properly.  I may not be able to fix it until tonight since I am at the trc meeting

**Comment by phlptp** [comment]
@Jacobhansens   try it again now.

**Pull request merged**
