### PR TITLE
Install MPI dependency and build

### PR DESCRIPTION
**Pull request by nightlark**
* Adds options to install-dependency script for building Open MPI and MPICH
* Builds MPI core on gcc-4.9.3 configuration

### CODE REVIEW

**Comment by phlptp** [comment]
How do we intend to use this in travis?  Daily build or part of the every commit CI?

**Comment by nightlark** [comment]
I think it would be good to have a configuration that at least builds the MPI core for commits made to develop/master (same with other cores/interfaces).

**Comment by phlptp** [comment]
can we have just one configuration that does that?   or do they all need to build mpi for that to work?  If it is just one, I am fine with adding a 4th configuration for that.

**Comment by nightlark** [comment]
Right now it is configured to build with MPI for only the gcc-4.9.3 configuration on each commit, regardless of the branch. That can be changed to limit it to only building with MPI if the commit (or PR) is to the develop/master branch -- though we should have a way to turn on MPI for all configurations (Linux, not OS X) for certain branches -- maybe if the branch name contains the term mpi?

**Comment by phlptp** [comment]
I think my preference would be on the gcc 6.3 build instead of the 4.9.4 build. since we are already stressing that one with the oldest supported build.  And there seems to be a bunch of cmake warnings coming in that should be cleared up before merging with develop.  Are there any tests we can run on Travis to verify it is working?

**Comment by nightlark** [comment]
There are some examples that could be run. A test suite for testing with the MPI core would be better -- I think with non-blocking HELICS calls it would be similar to the other test suites, and give an example of how someone could integrate use of the MPI core with an existing program that uses MPI.

**Comment by phlptp** [comment]
Did the clang+mpi work, and if so once you roll that back we can approve this

**Comment by nightlark** [comment]
Yep, it worked.

**Pull request merged**
