### PR TITLE
Fix readthedocs build

### LINKED ISSUE #656: github doc updates not showing in readthedocs
**Describe the bug**
Changes made to documentation at, e.g.: `HELICS-src/docs/index.md`
Do not show up at: https://helics.readthedocs.io/en/latest/

**Environment (please complete the following information):**
On-line documentation

### PR DESCRIPTION
**Pull request by kdheepak**
Fixes #656 

This also pins the readthedocs build as well, so it should prevent future issues. We'll have to update dependencies every now and then.

### CODE REVIEW

**Comment by kdheepak** [comment]
There's some additional issues here that I need to resolve: https://helics.readthedocs.io/en/kd-fix-readthedocs-build/

**Comment by kdheepak** [comment]
Okay, all the issues have been resolved. You can view the docs at the link above until this PR is merged, after which the default docs will contain all the updates.

**Comment by phlptp** [comment]
Is the codacy warning legitimate or a false positive?   it does look like you are importing the same thing twice.

**Comment by phlptp** [comment]
the top line on the docs looks a bit funny

Any way we could make those links work properly with the tags?

**Comment by kdheepak** [comment]
Okay, this is ready to merge now.

**Pull request merged**
