### PR TITLE
Some suggested documentation updates based on my install experience.

### PR DESCRIPTION
**Pull request by activeshadow**
I teased some of these out while trying to get the code to compile.

### CODE REVIEW

**Comment by activeshadow** [comment]
I did build an image, but only locally. I haven’t pushed it to Docker Hub.

**Comment by kdheepak** [comment]
I'll leave this open for now. I'll merge this along with some documentation changes that I have on my plate.

**Comment by phlptp** [comment]
I am hoping we can get a 1.3.1 release at some point next week.  We should merge it before then.

**Comment by kdheepak** [comment]
Sounds good!

**Comment by activeshadow** [comment]
@kdheepak feel free to use the Dockerfile I included in the documentation as the basis for a Dockerfile in the project that can be automatically built by Docker Hub or Quay or whatever Docker image host you want to use.

**Pull request merged**
