### PR TITLE
Java tests helics 2 0

### PR DESCRIPTION
**Pull request by shwethanidd**
Added helics error object mapping java_maps.i
Modified java tests to use correct API signatures.

### CODE REVIEW

**Comment by nightlark** [comment]
It looks like the main errors causing Travis/Appveyor failures are:
```
13/17 Test #19: Java_Helics_Api_tests ............***Timeout 220.00 sec
java.lang.Exception: federate object is not valid
	at com.java.helics.helicsJNI.helicsFederateFinalize(Native Method)
	at com.java.helics.helics.helicsFederateFinalize(helics.java:224)
	at JavaHelicsApiTests.main(JavaHelicsApiTests.java:558)
```

```
14/17 Test #20: Java_MessageFederate_test ........***Timeout 220.00 sec
Exception in thread "main" java.lang.Exception: cannot call register endpoint after entering initialization mode
	at com.java.helics.helicsJNI.helicsFederateRegisterEndpoint(Native Method)
	at com.java.helics.helics.helicsFederateRegisterEndpoint(helics.java:606)
	at TestMessageFederate.test_message_federate_endpoint_registration(TestMessageFederate.java:38)
	at TestMessageFederate.main(TestMessageFederate.java:117)
```

Fixing those two should make Appveyor (minus the zmq test that fails) and Travis GCC 6/Clang 3.6 builds pass.

**Comment by shwethanidd** [comment]
Looks like java tests pass in appveyor. @afisher1: Let's prioritize what needs to be fixed in Codacy/PR Quality Review. We can remove unnecessary test files such as TestValueFederate.java and TestMessageFilter.java

**Comment by afisher1** [comment]
Yes, I agree that the unnecessary test files should be removed. Also there are 4 unused local variables that need to be removed/commented out in JavaHelicsApiTests.java

**Comment by shwethanidd** [comment]
@afisher1: If everything seem fine, can you accept this pull request.

**Comment by phlptp** [comment]
I am going to merge this and see if the merged branch passes the java tests

**Pull request merged**
