### PR TITLE
propagate the flags to newly created interfaces and create a test cas…

### PR DESCRIPTION
**Pull request by phlptp**
…e to verify this.

- [x] I have reviewed the [Contributing Guidelines](../CONTRIBUTING.md)
- [x] I agree to license my contributions under the same license as in this repository
- [x] I have verified that the tests pass

### Description

Fixes issue #550

### Proposed changes

Fix issue #550 by adding a creation function inside of federate state that actually does the propagation.  And add a test case that verifies it.

### CODE REVIEW

**Comment by Jacobhansens** [comment]
@phlptp, I am not able to get this working on my system. I think I am not fully understanding the correct way to specify this flag. I current do the following in my JSON config file:

```
{
    "name": "dsoBus7",
    "log_level": 2,
    "uninterruptible": true,
    "coreType": "zmq",
    "coreName": "",
    "coreInit": "1",
    "period": 10.0,
    "timeDelta": 10.0,
    "strict_input_type_checking": true,
    "publications": [
     ... (more here)
     "subscriptions": [
     ... (more here)
}
```

However this does not enable the strict type checking. Can you let me know the correct way to set this through a configuration file?

**Comment by phlptp** [comment]
it might have worked if you had done "flags":"strict_input_type_checking"   but I made some updates that will allow what you had to work (I think).

**Comment by Jacobhansens** [comment]
setting `strict_input_type_checking` now works. One question I have is that I see this in federateInfo.cpp:

```
{"strict_type_checking", helics_handle_option_strict_type_checking},
   {"strict_type_matching", helics_handle_option_strict_type_checking},
   {"strict_input_type_checking", helics_handle_option_strict_type_checking},
   {"strict_input_type_matching", helics_handle_option_strict_type_checking},
   {"strictinputtypechecking", helics_handle_option_strict_type_checking},
   {"strictinputtypematching", helics_handle_option_strict_type_checking},
   {"stricttypechecking", helics_handle_option_strict_type_checking},
   {"stricttypematching", helics_handle_option_strict_type_checking},
   {"strict", helics_handle_option_strict_type_checking}};
```

Which seems to suggest I have multiple options for spelling when setting this flag but that is not supported. Do we intend to support more ways of spelling?

**Comment by Jacobhansens** [comment]
Okay that makes sense. I will approve now but in the future we should think about a more consistent way for checks on inputs like you mention

**Comment by phlptp** [comment]
As far as validation goes,  I have done it in other programs but with HELICS you have 4 or 5 layers sometimes all pulling different things from the files so it is challenging to figure out where to do the validation.

**Pull request merged**
