### PR TITLE
Python interface cmake build

### PR DESCRIPTION
**Pull request by nightlark**
- [x] I have reviewed the [Contributing Guidelines](../CONTRIBUTING.md)
- [x] I agree to license my contributions under the same license as in this repository
- [x] I have verified that the tests pass

# Description

Builds the Python interface without swig as a CMake library to avoid errors on systems that have read-only pip installations.

### CODE REVIEW

**Comment by nightlark** [comment]
I think all of our builds use the oldest supported cmake version (3.4.3), but only one of the builds uses the pre-generated swig headers.

**Comment by phlptp** [comment]
Should we have a build with a newer cmake?

**Comment by nightlark** [comment]
Actually, I was wrong -- the Windows build on Appveyor uses CMake 3.12, but it uses swig. I don't think the added time for an additional build on every commit is worth it (maybe for PRs to master), since most of the failures are from the generated files not getting updated; one of the builds detecting changes that result in different generated files would be useful.

**Comment by phlptp** [comment]
Someday I would love to see an automated system that checks and regenerates the files for the non-swig builds and makes a PR with the updated files.

**Comment by phlptp** [comment]
but you are right we probably don't need a separate build for that test.

**Pull request merged**
