### PR TITLE
Fix xcode 6.4 build

### PR DESCRIPTION
**Pull request by kdheepak**

### CODE REVIEW

**Comment by kdheepak** [comment]
Closes #28.

**Comment by phlptp** [comment]
This doesn't appear to have fixed the issue yet.  The xcode 6.4 build is still failing

**Comment by kdheepak** [comment]
I'm looking into this.

**Comment by kdheepak** [comment]
@phlptp Thanks for checking on this. I'm not sure how this happened, but the changes I'd made must have got reverted when I get a rebase onto develop. I've added the changes back and now it [builds successfully on both](https://travis-ci.org/GMLC-TDC/HELICS-src/builds/312223113).

**Comment by phlptp** [comment]
@kdheepak what is pcre?

**Comment by kdheepak** [comment]
It's Perl Compatible Regular Expressions. The error messages I got without upgrading this on Travis OSX indicated that this was the problem when building swig from source.

**Comment by kdheepak** [comment]
See log for this [build](https://travis-ci.org/GMLC-TDC/HELICS-src/jobs/311957556) for the error message.

```
checking whether to enable PCRE support... yes

checking whether to use local PCRE... no

checking for a sed that does not truncate output... /usr/bin/sed

checking for pcre-config... no

configure: error: in `/tmp/swig-3.0.10':

configure: error: 

        Cannot find pcre-config script from PCRE (Perl Compatible Regular Expressions)

        library package. This dependency is needed for configure to complete,

        Either:

        - Install the PCRE developer package on your system (preferred approach).

        - Download the PCRE source tarball, build and install on your system

          as you would for any package built from source distribution.

        - Use the Tools/pcre-build.sh script to build PCRE just for SWIG to statically

          link against. Run 'Tools/pcre-build.sh --help' for instructions.

          (quite easy and does not require privileges to install PCRE on your system)

        - Use configure --without-pcre to disable regular expressions support in SWIG

          (not recommended).

See `config.log' for more details

make: *** No targets specified and no makefile found.  Stop.
```

**Pull request merged**
