### PR TITLE
Test python extension on travis

### PR DESCRIPTION
**Pull request by kdheepak**
- Imports helics extension on Travis in Python: `import helics`
- Runs the version number of HELICS function in Python: `helics.helicsGetVersion()`

### CODE REVIEW

**Comment by kdheepak** [comment]
Closes #62. More tests can be added in the future.

**Comment by kdheepak** [comment]
[Python tests run successfully](https://travis-ci.org/GMLC-TDC/HELICS-src/jobs/337078093#L2545-L2565).

**Comment by phlptp** [comment]
looks like there is still some issues with the Mac builds with this PR.  Just for reference the test is basically loading the library and getting the version string?

**Comment by kdheepak** [comment]
That is correct. I figured we can add other tests later. This just verifies that the Python extension builds, links and can be imported correctly in Python version 3.6.3.

**Comment by kdheepak** [comment]
I'll make all the changes required for the Mac builds and comment here.

**Comment by kdheepak** [comment]
Well, it turns out the [Mac builds](https://travis-ci.org/GMLC-TDC/HELICS-src/jobs/337264140) [are passing](https://travis-ci.org/GMLC-TDC/HELICS-src/jobs/337264141). I've restarted the gcc build that failed in the PR ci and the clang build that failed in the push ci (both the clang build in the PR ci and the gcc build in the push ci had passed).

**Comment by kdheepak** [comment]
@phlptp This is ready to merge now.

**Comment by kdheepak** [comment]
@phlptp @nightlark This is ready to merge now.

**Comment by phlptp** [comment]
still shows up as a big red ! when I look, at the PR check on Travis for the xcode builds.  Am I missing something?

**Comment by kdheepak** [comment]
The gcc build for the push ci failed this time. See the [PR ci page](https://travis-ci.org/GMLC-TDC/HELICS-src/builds/337264136), everything passes there.

**Comment by kdheepak** [comment]
Sorry! I was looking at the wrong PR!

**Comment by kdheepak** [comment]
I'll comment here when I fix this.

**Comment by kdheepak** [comment]
Okay, this is now [complete](https://travis-ci.org/GMLC-TDC/HELICS-src/builds/337292655).

**Comment by kdheepak** [comment]
Any idea why the Windows builds are failing?

**Comment by phlptp** [comment]
```
3: C:/projects/helics-src/tests/helics/application_api/test-filters.cpp(171): fatal error: in "filter_tests/message_filter_function2/_1": critical check mFed->hasMessage (p2) has failed
3: Failure occurred in a following context:
3:     core_type = ipc_2; 
```

This is the thing I have been trying to figure out for quite a while and I hope is mostly addressed in #146.  That particular bug doesn't show up in debug mode, and only shows up on low core count systems.  so it has been mostly an exercise in theoretical execution to figure out.

**Comment by phlptp** [comment]
@kdheepak I think you can merge this when you are ready

**Pull request merged**
