### PR TITLE
Java HELICS API Tests

### PR DESCRIPTION
**Pull request by afisher1**
This pull request contains a file that calls the Java HELICS API functions and asserts the results. This file contains tests that will close issue #306. This file can also be used to determine if issue #348 has been fixed.

### CODE REVIEW

**Comment by afisher1** [comment]
I've addressed all the warnings in Codacy except the first one. It complains that the main function is too long. I just wrote all the tests inside of the main function as it was the most straight forward approach for testing the api. I think we can just ignore it.

**Comment by phlptp** [comment]
Is this test running on Travis?  @nightlark  if not can you add it to the tests that run regularly?

**Comment by phlptp** [comment]
the review is only showing 1 file changed is that correct?

**Comment by phlptp** [comment]
@afisher1  would it be possible to go through and fix the warnings in the other Java test files?

**Comment by nightlark** [comment]
The tests aren't running - it looks like the CMakeLists.txt file doesn't have any targets added that use the JavaHelicsApiTests.java source file. There's also another source file named ApplicationApiTest.java which is a pretty similar name -- but that one seems to just test a single value federate publishing a value and advancing time; thoughts on renaming that ApplicationApiTest to something else and calling JavaHelicsApiTests ApplicationApiTest instead?

Also, something more general with the Java tests, I noticed that TestValueFederate.java has a large number of methods that don't get called from its main method -- are the tests in there a work in progress (I don't see any open issues related to them, closest is #315), or is there something special needed to run them (I noticed that the Test*.java files all import java.lang.reflect.Method)?

**Comment by phlptp** [comment]
@afisher1  can you work with @nightlark  to make sure all the java tests are running in Travis/appveyor and  see if we can clean up some of the files if they are duplicative or redundent?

**Comment by afisher1** [comment]
@nightlark  JavaHelicsApiTests.java is the new test script I built that actually asserts functionality of the java bindings for helics. All the other ones were incomplete works from Jeff basically. They called very few functions of the api and didn't validate that they did what they were supposed to. We can basically get rid of them and just use my file. How do we get my file to automatically be run on travis.

**Comment by nightlark** [comment]
The CMakeLists.txt file in the java tests folder needs a new test added, and the name of the test gets added to the line at the bottom of the cmake file to give it the Java label.

**Comment by nightlark** [comment]
The gcc 4.9.3 build had a set of failed assertions, but on rerunning the build it passed. On the PR build, clang has a similar set of assertions that failed. I'm going to restart the build -- below is a copy of the log for the failed run.

```
10: Test command: /usr/lib/jvm/java-8-oracle/bin/java "-Djava.library.path=/home/travis/build/GMLC-TDC/HELICS-src/build/swig/java" "-classpath" "/home/travis/build/GMLC-TDC/HELICS-src/build/swig/java/buildjar/helics-1.2.0.jar:/home/travis/build/GMLC-TDC/HELICS-src/build/tests/java_helics" "JavaHelicsApiTests"
10: Test timeout computed to be: 1500
10: Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
10: java.lang.AssertionError: ep2MsgCount != 3
10: 	at JavaHelicsApiTests.helicsAssert(JavaHelicsApiTests.java:11)
10: 	at JavaHelicsApiTests.main(JavaHelicsApiTests.java:382)
10: java.lang.AssertionError: fed1MsgCount != 2
10: 	at JavaHelicsApiTests.helicsAssert(JavaHelicsApiTests.java:11)
10: 	at JavaHelicsApiTests.main(JavaHelicsApiTests.java:419)
10: java.lang.AssertionError: sub1Updated != 1
10: 	at JavaHelicsApiTests.helicsAssert(JavaHelicsApiTests.java:11)
10: 	at JavaHelicsApiTests.main(JavaHelicsApiTests.java:462)
10: java.lang.AssertionError: sub2UpdateTime != 1.0e9
10: 	at JavaHelicsApiTests.helicsAssert(JavaHelicsApiTests.java:11)
10: 	at JavaHelicsApiTests.main(JavaHelicsApiTests.java:466)
10: java.lang.AssertionError: sub5Value[0] != 1
10: 	at JavaHelicsApiTests.helicsAssert(JavaHelicsApiTests.java:11)
10: 	at JavaHelicsApiTests.main(JavaHelicsApiTests.java:471)
10: java.lang.AssertionError: sub2Real[0] != 5.6
10: 	at JavaHelicsApiTests.helicsAssert(JavaHelicsApiTests.java:11)
10: 	at JavaHelicsApiTests.main(JavaHelicsApiTests.java:477)
10: java.lang.AssertionError: sub2Imag[0] != -0.67
10: 	at JavaHelicsApiTests.helicsAssert(JavaHelicsApiTests.java:11)
10: 	at JavaHelicsApiTests.main(JavaHelicsApiTests.java:480)
10: java.lang.AssertionError: sub1Value[0] != 457.234
10: 	at JavaHelicsApiTests.helicsAssert(JavaHelicsApiTests.java:11)
10: 	at JavaHelicsApiTests.main(JavaHelicsApiTests.java:485)
10: java.lang.AssertionError: sub4Value[0] != 1
10: 	at JavaHelicsApiTests.helicsAssert(JavaHelicsApiTests.java:11)
10: 	at JavaHelicsApiTests.main(JavaHelicsApiTests.java:490)
10: java.lang.AssertionError: !sub7PointString.contains("Blah Blah")
10: 	at JavaHelicsApiTests.helicsAssert(JavaHelicsApiTests.java:11)
10: 	at JavaHelicsApiTests.main(JavaHelicsApiTests.java:498)
10: java.lang.AssertionError: sub7PointLength[0] != 9
10: 	at JavaHelicsApiTests.helicsAssert(JavaHelicsApiTests.java:11)
10: 	at JavaHelicsApiTests.main(JavaHelicsApiTests.java:501)
10: java.lang.AssertionError: !sub3ValueString.contains("Mayhem")
10: 	at JavaHelicsApiTests.helicsAssert(JavaHelicsApiTests.java:11)
10: 	at JavaHelicsApiTests.main(JavaHelicsApiTests.java:511)
10: java.lang.AssertionError: sub3Length[0] != 6
10: 	at JavaHelicsApiTests.helicsAssert(JavaHelicsApiTests.java:11)
10: 	at JavaHelicsApiTests.main(JavaHelicsApiTests.java:514)
10: java.lang.AssertionError: sub3ValueSize != 6
10: 	at JavaHelicsApiTests.helicsAssert(JavaHelicsApiTests.java:11)
10: 	at JavaHelicsApiTests.main(JavaHelicsApiTests.java:518)
10: 80 of 94 tests passed.
10: 85% successfull.
10: 14 tests failed.
2/5 Test #10: Java_Helics_Api_tests ............***Failed    0.63 sec
```

**Comment by nightlark** [comment]
The PR build with clang looks like it is failing consistently.

**Pull request merged**
