### PR TITLE
HELICS installation link update

### PR DESCRIPTION
**Pull request by trevorhardy**
### Description

Updates links to installation guide on readthedocs for User Guide

### Proposed changes
Updated links

### CODE REVIEW

**Comment by phlptp** [comment]
it looks like there might be a few other places where a similar change is necessary queries.md and FederateInfo.md.  Probably should make the change in those files as well.

**Comment by trevorhardy** [comment]
Good catch, Phil. Using this handy feature called "search" (have you heard of it?) I think I was able to get all of them in the user-guide folder.

**Comment by phlptp** [comment]
Have you pushed the updates.  I don't see anything the initial commits.

**Comment by trevorhardy** [comment]
Sorry; updates have now been pushed.

**Comment by phlptp** [comment]
I will merge once the checks complete

**Pull request merged**
