### PR TITLE
update the jsoncpp library,

### PR DESCRIPTION
**Pull request by phlptp**
change the namespace so it is a little easier to maintain in the future.

Now Json::  is a member of the helics::Json::  instead of Json_helics   this should make things simpler to update in the future and be more maintainable and a little more consistent with the original usage as long as you are in the helics namespace, but still prevent namespace conflicts.

- [x] I have reviewed the [Contributing Guidelines](../CONTRIBUTING.md)
- [x] I agree to license my contributions under the same license as in this repository
- [x] I have verified that the tests pass

### Description

Update Jsoncpp library with upstream changes and new namespace to make it a little easier to update in the future.

### CODE REVIEW

**Comment by nightlark** [comment]
Instead of modifying the ThirdParty jsoncpp library to include the namespace, what about wrapping the #include for jsoncpp in `namespace helics { ... }`? Then we might not need a modified copy of the upstream library.

**Comment by phlptp** [comment]
I tried that at one point but you run into all sorts of chaos with the headers that jsoncpp includes then also being wrapped in that same namespace and then the functions in jsoncpp not in the namespace failing.  and all sorts of other chaos in the program, and even if it did work ending up with an essentially duplicated std

**Comment by nightlark** [comment]
So is the naming conflicts referring to other programs using helics that use their own copy of jsoncpp?

**Comment by phlptp** [comment]
I ran into the issue with GridDyn and helics-fmi

**Comment by phlptp** [comment]
I would also note that cereal does the same thing in wrapping rapidJson internally.

**Comment by phlptp** [comment]
I don't know that I would trust an automated script  as some of the process involves adapting to upstream changes in the cmake and code,  they are all one time things and automating it would probably cause more problems than it solves.    Some documentation would probably be in order though.

**Pull request merged**
