### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by kdheepak**

### CODE REVIEW

**Comment by phlptp** [comment]
What is the reasoning to change from RST to MD?

**Comment by phlptp** [comment]
So are we getting rid of all rst in the repo?

**Comment by kdheepak** [comment]
RST is in my opinion more difficult to read as raw files and write. MD is also much more commonly used. I used Github search to compare results that contained README with a suffix .md and .rst, Markdown has over 2 million results where as RST has around a tenth of that. 

Example for code snippets:

In RST

```
.. code-block:: bash

    brew tap GMLC-TDC/helics
    brew install helics
```

RST is sensitive to whitespace. So for example, `..code-block` will not work.

In MD

````
```
brew tap GMLC-TDC/helics
brew install helics
```
````

Another example for links.

In RST

```

Install brew_. It is a package manager for MacOS.

.. _brew: https://brew.sh/
```

This renders as the following.

> Install [brew](https://brew.sh). It is a package manager for MacOS.

In Markdown

```
Install [brew](https://brew.sh). It is a package manager for MacOS.
```

Markdown is used in Github issues, PR and a large majority of README files. Switching back and forth between MD and RST is cognitive effort I'd like to avoid. I find that even after using RST for projects, I end up referring the manual often. Using Markdown in Sphinx also renders on Github more correctly than some of the things in Sphinx RST. 

Finally, Pandoc Markdown has a lot of features and is [very well documented](https://pandoc.org/MANUAL.html).

**Comment by kdheepak** [comment]
Yes, we are getting rid of all RST files.

**Pull request merged**
